### ISSUE TITLE
[FEATURE] Promotion of repository

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/Algorithms-Explanation#230]
### Detailed description

Due having a ton of entries, it seems like a lot of the entries have no explanation accompanying them, leaving them vague and confusing to say the least! So now obviously, it's not easy to write documentation for the same, with people being more interested in writing code (which is understandable). But I was suggesting if we could maybe promote this repository (not in a bad sense) to the people who are contributing to other repositories of this organisation to maybe also spend some time helping out on this portion of the organisation to revive the explanations to make the site _actually_ helpful, instead of being a place to just get code of algorithms from, kinda.

### Context

_Context provided in description_

### Possible implementation

The way we could promote or so on the top of my mind are:
- Drawing attention to this repository on the website, by adding some non-intrusive pop-ups and urging interested users to contribute
- Promoting contribution to this repository during Hacktoberfest, since it is not that difficult to really add one page of documentation for the swathes of PRs this organisation gets anyways

### Additional information

Please note that these aren't all possible ways to promote the repo, so you (the person reading this) should also probably try to come up with some other ways.
Some possible issues with the promotion of repository:
- Our entries aren't that... organised to say the least. They are indeed a mess, I'll admit, and it can cause a few issues and confusion
- If we promote the repo during Hacktoberfest, then we'll definitely get tons of useless PRs with a bunch of single lines filled in, or improper formatting, which may bog down the few maintainers we have for this repository, who may also be dealing with swathes of spam PRs in other repositories for Hacktoberfest, which will be insane for the maintainers.

These are atleast some of the things we'll need to consider while trying to promote this repo, along with some other things which didn't cross my mind while typing this issue out. I'd like to have a proper discussion for this here. But regardless, we definitely are in dire need of more documentation for the site.

**Comment by appgurueu** [comment]
Some thoughts:

* We need more maintainers for this. Last Hacktoberfest I did not have enough time to address everything properly in the JS/TS repos. I will probably have even less time this year.
* Good code can ideally be pretty self-explanatory (esp. with comments) regarding *how* an algorithm / data structure works.
* For many algorithms and data structures, there are already relatively good resources that could be linked to - Wikipedia articles, various other websites that explain algorithms decently, textbooks, maybe even papers. (We should perhaps consider using archive.org to pin certain versions of websites that are likely to change.)
* A good explanation is more than an explanation of how a particular implementation works. Ideally, there would be a proper proof and runtime analysis. I recommend first thoroughly understanding algorithms, then writing explanations from that understanding.
* I agree that everything is fairly disorganized. This leads to problems, esp. with how we display stuff. For example the quick sort explanation claims a space complexity of O(log n). This is not the case for all our quicksort implementations (for example it isn't the case for the Python explanation). Pretending that algorithms do the same thing just because they have the same name is naive.
* Promoting this repo might make sense. I don't know what the best way to go about this would be, esp. if we want to attract experienced contributors which are also good at explaining. I'm also wary of Hacktoberfest.

**Comment by SpiderMath** [comment]
> Some thoughts:
> 
> * We need more maintainers for this. Last Hacktoberfest I did not have enough time to address everything properly in the JS/TS repos. I will probably have even less time this year.

I guess we should probably keep this away from Hacktoberfest in that case? Since we have such an acute shortage of maintainers in the organisation.
> * For many algorithms and data structures, there are already relatively good resources that could be linked to - Wikipedia articles, various other websites that explain algorithms decently, textbooks, maybe even papers. (We should perhaps consider using archive.org to pin certain versions of websites that are likely to change.)

Are you suggesting like adding links to explanations on other websites instead of adding like our own ones? That actually sounds like a good way to reduce a bit of the load from adding documentation in that case. Just one thing, I think we'll probably need to make some changes in website layout to accommodate this setup.
> * A good explanation is more than an explanation of how a particular implementation works. Ideally, there would be a proper proof and runtime analysis. I recommend first thoroughly understanding algorithms, then writing explanations from that understanding.

I think we should add that in our `CONTRIBUTING.md`? That way more people shall know they're do to the same.
> * I agree that everything is fairly disorganized. This leads to problems, esp. with how we display stuff. For example the quick sort explanation claims a space complexity of O(log n). This is not the case for all our quicksort implementations (for example it isn't the case for the Python explanation). Pretending that algorithms do the same thing just because they have the same name is naive.

Is it possible for us to maybe get all of the maintainers together to iron out such issues? Or maybe change the user interface on the website to show algorithms with various time complexities for each language? Both of these would be helpful to deal with the inconsistency issue.

> * Promoting this repo might make sense. I don't know what the best way to go about this would be, esp. if we want to attract experienced contributors which are also good at explaining. I'm also wary of Hacktoberfest.

Maybe we can prompt people to do this on the website directly? We could also ask people to do so in the READMEs of repositories with most activity (prolly JS/TS/Python repos) and we could maybe remove those for the duration of Hacktoberfest. I'm not sure most people contributing to other repositories know about the existence of this repository, since there's quite a few repos under this organisation (for example, I just came to know a few days back that there's a MATLAB-Octave repo 🤨). If its existence is shared more, this repo will get more attention and that *may* lead to more contributions (hopefully)
